# Generated by Django 3.0.5 on 2022-11-22 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('birthDay', models.DateTimeField(verbose_name='誕生日')),
            ],
        ),
    ]
