# Generated by Django 3.0.5 on 2022-12-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
